src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use App\Entity\Modele;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $serie = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_mise_en_marche = null;

    #[ORM\Column]
    private ?int $prix_jour = null;

    #[ORM\OneToMany(targetEntity: Location::class, mappedBy: 'voiture')]
    private Collection $locations;

    #[ORM\ManyToOne(inversedBy: 'voitures')]
    private ?Modele $modele = null;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
        // $this->modele stays null by default; it is NOT a collection
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSerie(): ?int
    {
        return $this->serie;
    }

    public function setSerie(int $serie): static
    {
        $this->serie = $serie;
        return $this;
    }

    public function getDateMiseEnMarche(): ?\DateTimeInterface
    {
        return $this->date_mise_en_marche;
    }

    public function setDateMiseEnMarche(\DateTimeInterface $date_mise_en_marche): static
    {
        $this->date_mise_en_marche = $date_mise_en_marche;
        return $this;
    }

    public function getPrixJour(): ?int
    {
        return $this->prix_jour;
    }

    public function setPrixJour(int $prix_jour): static
    {
        $this->prix_jour = $prix_jour;
        return $this;
    }

    /**
     * @return Collection<int, Location>
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): static
    {
        if (!$this->locations->contains($location)) {
            $this->locations->add($location);
            $location->setVoiture($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): static
    {
        if ($this->locations->removeElement($location)) {
            if ($location->getVoiture() === $this) {
                $location->setVoiture(null);
            }
        }

        return $this;
    }

    public function getModele(): ?Modele
    {
        return $this->modele;
    }

    public function setModele(?Modele $modele): static
    {
        $this->modele = $modele;
        return $this;
    }
}

src/Form/VoitureType.php
<?php

namespace App\Form;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use App\Entity\Voiture;
use App\Entity\Modele;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoitureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('serie' , TextType::class)
            ->add('date_mise_en_marche', DateType::class)
            ->add('modele', TextType::class)
            ->add('prix_jour', NumberType::class)
            ->add('modele', EntityType::class, [
                'class' => Modele::class,
                'choice_label' => 'libelle',
                'placeholder' => 'Choisir un modèle',
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Voiture::class,
        ]);
    }
}

src/Controller/VoitureController.php
<?php

namespace App\Controller;

use App\Entity\Voiture;
use App\Form\VoitureType;
use App\Repository\VoitureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VoitureController extends AbstractController
{
    #[Route('/voitures', name: 'app_voiture')]
    public function listeVoiture(Request $request, VoitureRepository $vr): Response
    {
        $modeleId = $request->query->getInt('modele', 0) ?: null;

        $voitures = $modeleId
            ? $vr->findByModele($modeleId)
            : $vr->findAll();

        return $this->render('voiture/listeVoiture.html.twig', [
            'listeVoiture' => $voitures,
        ]);
    }

    #[Route('/voiture/add', name: 'app_voiture_add')]
    public function addVoiture(Request $request, EntityManagerInterface $em): Response
    {
        $voiture = new Voiture();
        $form = $this->createForm(VoitureType::class, $voiture);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($voiture);
            $em->flush();

            // redirect to the list route name you actually have
            return $this->redirectToRoute('app_voiture');
        }

        // make sure this matches your real Twig filename
        return $this->render('voiture/addVoiture.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    #[Route('/voiture/delete/{id}', name: 'deleteVoiture')]
    public function deleteVoiture(int $id, EntityManagerInterface $em): Response
    {
        $voiture = $em->getRepository(Voiture::class)->find($id);

        if ($voiture) {
            $em->remove($voiture);
            $em->flush();
        }

        return $this->redirectToRoute('app_voiture');
    }
    #[Route('/voiture/update/{id}', name: 'updateVoiture')]
    public function updateVoiture(int $id, Request $request, EntityManagerInterface $em): Response
    {
        $voiture = $em->getRepository(Voiture::class)->find($id);

        if (!$voiture) {
            throw $this->createNotFoundException('Voiture non trouvée');
        }

        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute('app_voiture');
        }

        return $this->render('voiture/update_voiture.html.twig', [
            'editFormVoiture' => $form->createView(),  // ← Nom cohérent avec la vue
            'voiture' => $voiture,
        ]);
    }



}

templates/voiture/addVoiture.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button type="submit">Add voiture</button>
{{ form_end(form) }}

templates/voiture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VoitureController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! </h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/car-rental-project/src/Controller/VoitureController.php'|file_link(0) }}">src/Controller/VoitureController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/car-rental-project/templates/voiture/index.html.twig'|file_link(0) }}">templates/voiture/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/voiture/listeVoiture.html.twig
<h1>Liste des voitures</h1>

<form method="get" action="{{ path('app_voiture') }}">
    <label for="modele">Filtrer par modèle (ID):</label>
    <input type="number" name="modele" id="modele" value="{{ app.request.get('modele') }}">
    <button type="submit">Filtrer</button>
</form>
<br>

<table border="1">
    <tr>
        <td>Serie</td>
        <td>Date Mise en Marche</td>
        <td>Modele</td>
        <td>Actions</td>
    </tr>
    {% for v in listeVoiture %}
        <tr>
            <td>{{ v.serie }}</td>
            <td>{{ v.dateMiseEnMarche | date('Y-m-d') }}</td>
            <td>{{ v.modele ? v.modele.libelle : '' }}</td>
            <td>
                <a href="{{ path('deleteVoiture', {'id': v.id}) }}">Supprimer</a>
                <a href="{{ path('updateVoiture', {'id': v.id}) }}">Update</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/voiture/update_voiture.html.twig
{{ form_start(editFormVoiture) }}
    {{ form_widget(editFormVoiture) }}
<button type="submit">Enregistrer</button>
{{ form_end(editFormVoiture) }}